config/routes.rb
Rails.application.routes.draw do
  root 'portfolios#index'
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'


  get 'blogs/mining', to: 'blogs#mining'
  get 'blogs/technology', to: 'blogs#technology'

  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    member do
      post :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    # Now, you can run something like this on rails console:
    # Blog.last.publish! <--- Last blog.status == 'published'

    belongs_to  :topic

    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of   :title, :body

    def self.mining
        where(topic_id: 3)
    end

    scope :technology, -> { where(topic_id: 4) }

end

app/models/concerns/placeholder.rb
module Placeholder
    extend ActiveSupport::Concern

    def self.image_generator(height:, width:)
        "http://placehold.it/#{height}x#{width}"
    end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies

    include Placeholder

    validates_presence_of   :title, :body, :main_image, :thumb_image

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height:600,width:400)
        self.thumb_image ||=  Placeholder.image_generator(height:350,width:200)
    end

end

app/models/skill.rb
class Skill < ApplicationRecord
    include Placeholder

    validates_presence_of   :title, :percent_utilized

    after_initialize :set_defaults

    def set_defaults
        self.badge ||= Placeholder.image_generator(height: 250, width: 250)
    end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates_presence_of   :title
    has_many    :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  def technology
    @blogs = Blog.technology
  end

  def mining
    @blogs = Blog.mining
  end

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  def toggle_status
    @blog.published? ? @blog.draft! : @blog.published!
    redirect_to blogs_path
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
    @portfolios = Portfolio.all
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(get_params)
    if @portfolio.save
      flash[:success] = "Portfolio created!"
      redirect_to portfolios_path
    else
      render 'new'
    end
  end

  private

  def get_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog), method: :post %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/mining.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog), method: :post %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/technology.html.erb
<p id="notice"><%= notice %></p>

<h1>Mining blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog), method: :post %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampPortfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/portfolios/index.html.erb
<% @portfolios.each do |portfolio| %>
    <div>
        <h3><%= portfolio.title %></h3>
        <h5><%= portfolio.subtitle %></h5>
        <p><%= portfolio.body %></p>
        <%= image_tag portfolio.thumb_image unless portfolio.thumb_image.nil? %>
        <hr>
    </div>
<% end %>

app/views/portfolios/new.html.erb
<h3>New portfolio item.</h3>

<%= form_for @portfolio do |form| %>
    <p>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </p>
    <p>
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle %>
    </p>
    <p>
        <%= form.label :body %>
        <%= form.text_area :body %>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.any? %>
    <ul>
    <% flash.each do |key, msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>